steps:
#This step builds the container image.
  - name: "gcr.io/cloud-builders/docker"  #gcr is the google container registry
    id: "build"
    args:
      - "build"
      - "-t"
      - "gcr.io/project-funky-flex/stedi-michael:latest"
      - "."
      
  - name: "gcr.io/cloud-builders/docker"
    id: push
    args:
      - "push"
      - "gcr.io/project-funky-flex/stedi-michael:latest"

  - name: 'gcr.io/cloud-builders/gke-deploy'
    id: Deploy
    args:
    - run
    - --filename=manifest.yaml
    - --image=gcr.io/project-funky-flex/stedi-michael:latest
    - --location=us-east4-b
    - --output=/tmp/outputdev
    - --cluster=cluster-1
  
  - name: "gcr.io/cloud-builders/docker"
    id: run
    args:
      - "run"
      - "gcr.io/project-funky-flex/stedi-michael:latest"
