steps:
#This step builds the container image.
  - name: "gcr.io/cloud-builders/docker"  #gcr is the google container registry
    id: "build"
    args:
      - "build"
      - "-t"
      - "gcr.io/$PROJECT_ID/stedi-tests-micahel:latest"
      - "."
  - name: "gcr.io/cloud-builders/docker"
    id: push
    args:
      - "push"
      - "gcr.io/$PROJECT_ID/stedi-tests-michael:latest"