#© 2021 Sean Murdock

apiVersion: apps/v1
kind: Deployment
metadata:
  name: michael-stedi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: michael-stedi
  template:
    metadata:
      labels:
        app: michael-stedi
    spec:
      containers:
        - name: michael-stedi
          image: gcr.io/project-funky-flex/stedi-michael:latest
          command: ["npm"]
          args: ["run","start"]
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: ".125"
              memory: "500Mi"
            requests:
              cpu: ".1"
              memory: "250Mi"
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 3
            periodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: michael-stedi
spec:
  selector:
    app: michael-stedi
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000